### PR TITLE
Podcast Module + Grid Layout (Watch Page)

### LINKED ISSUE #214: Replace Horizontal Scroll List with Grid Layout (Watch Page)
See: https://www.figma.com/file/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=289%3A25

In addition to the switch to a grid layout, horizontal lines need to be added above headers too.

### PR DESCRIPTION
**Pull request by JonEsparaz**
Adds podcasts to the bottom of the video player.

Diverges from Figma design to follow [Apple guidelines](https://www.apple.com/itunes/marketing-on-podcasts/identity-guidelines.html). Tested on Chrome, Firefox, Safari, Edge.

Here's a couple screenshots:

image

...when menu is open:

image

@deeinstereo let me know if the above is ok.

Additional:
- fixes nested button DOM warning in `VideoPlayer.tsx` that I missed
- adjusts "More From This Series" to better match Figma (further changes to come in another PR)

Edit: resolves #214

### CODE REVIEW

**Comment by JonEsparaz** [comment]
Also adding [https://github.com/themeetinghouse/web/pull/202/commits/7594b8c9c32b5b8d61263afb78a4c149b8bbcfa1](https://github.com/themeetinghouse/web/pull/202/commits/7594b8c9c32b5b8d61263afb78a4c149b8bbcfa1) to this PR to avoid a potential merge conflict.

This implements the grid layout on the watch page.

**Comment by deeinstereo** [comment]
@JonEsparaz looks really good! I'm curious if "More Ways to Listen" is too much copy for the button. What is we just wrote RSS Feed instead?

**Comment by JonEsparaz** [comment]
@deeinstereo not sure if RSS feed is technically correct, but I agree something shorter is probably better. Figma says “Subscribe”, which isn’t the worst idea. Perhaps just “Listen”? In any case it’s quick and easy to change, so just let me know.

**Comment by deeinstereo** [comment]
@JonEsparaz good point. Let's go with LISTEN, I think more might be a little too broad. Thanks!

**Comment by JonEsparaz** [comment]
> @JonEsparaz good point. Let's go with LISTEN, I think more might be a little too broad. Thanks!

@deeinstereo all caps?

**Comment by deeinstereo** [comment]
@JonEsparaz sure! Let's try all caps. If you try that and it looks to yelly then just do sentence case. No need to triple check with me. 

Thanks!

**Comment by GeorgeBellTMH** [comment]
Is this one ready?

**Comment by GeorgeBellTMH** [comment]
oh, just saw the no need to triple check...LGTM

**Comment by deeinstereo** [comment]
@JonEsparaz you son of a gun! It's beautiful! Just experienced it on the prod page. WOOOO!

**Comment by deeinstereo** [comment]
@JonEsparaz one small thing I did notice, the episode numbers seem to have disappeared. They used to appear right beside the title eg. "1. Love is the Law", can we bring that back so that people can see the sequential order?

**Comment by JonEsparaz** [comment]
@deeinstereo yup. I took em out since they didn’t appear on Figma, but I’ll definitely add them back 👍

**Comment by JonEsparaz** [comment]
While I'm at it @deeinstereo should the videos appear newest to oldest or oldest to newest?

**Comment by JonEsparaz** [comment]
> While I'm at it @deeinstereo should the videos appear newest to oldest or oldest to newest?

@deeinstereo bump.

**Comment by deeinstereo** [comment]
@JonEsparaz confirming what we talked about. In the master all teaching videos playlist, newest to oldest, in each individual teaching series, oldest to newest.

**Comment by JonEsparaz** [comment]
> @JonEsparaz confirming what we talked about. In the master all teaching videos playlist, newest to oldest, in each individual teaching series, oldest to newest.

Noted in #225

**Pull request merged**
