### PR TITLE
Revert "Add types to Map components"

### PR DESCRIPTION
**Pull request by JonEsparaz**
There are a ton of breaking changes in the PR that prevent localhost from compiling. Reverting so @deeinstereo can continue his work. I'll get a proper patch later.

Reverts themeetinghouse/web#337

### CODE REVIEW

**Comment by nikklassen** [comment]
I can fix the bad merge and the unused import. Was there anything else you noticed?

**Comment by JonEsparaz** [comment]
That should be it. I was running into issues with the <Map/> component (which is where the "ton" wording came from), but I can't recreate. My apologies if there was extra cause for concern.

**Comment by GeorgeBellTMH** [comment]
Also, I need to apologize, I fixed it right after I merged it but forgot to check in the changes..

**Comment by nikklassen** [comment]
Is adding Github actions to do the build on PRs an option? With the number of changes this repo has the free tier should work. I wrote tests for another change but broke them almost immediately because I forgot to run them again.

**Pull request merged**
