### PR TITLE
Apply Feedback on App Promo UI

### LINKED ISSUE #739: Download App Notes prompt new issue
Jon told me to make it a new issue. 

You know what to do ;)

### PR DESCRIPTION
**Pull request by JonEsparaz**
Closes #739.

### CODE REVIEW

**Comment by JonEsparaz** [comment]
@deeinstereo if want to play around with this in Dev Tools (on different screen sizes, etc), on the command line (in the `web` repo), run:

- `git fetch origin pull/740/head:app-promo-feedback`
- `git checkout app-promo-feedback`
- `npm start`

When you are done, run:
- `git checkout master`

**Comment by deeinstereo** [comment]
@JonEsparaz thanks for this! PS>> Maybe one more change, I was doing some more research and I noticed the word OPEN being used instead of Download because of how long download is and how hard it is to fit it into a button. Any chance we can use OPEN instead and that load the app store?

**Comment by deeinstereo** [comment]
@JonEsparaz yup, just a tiny bit, also, any chance you can adjust the kerning (space between the letters) on Open, I think it's at 0, setting it to 5 will give them a bit more space and make it a little easier to read on smaller screens

**Pull request merged**
