### PR TITLE
Schema fixes

### PR DESCRIPTION
**Pull request by JonEsparaz**
@GeorgeBellTMH getting rid of that key directive. Also, there's an issue with the series connection since seriesId is a required field, so notes are broken at the moment... This should fix.

### CODE REVIEW

**Comment by GeorgeBellTMH** [comment]
All fields provided to an @connection must be non-null scalar or enum fields....I've changed it back to required...

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH we've still got a backwards compatibility issue tough, notes aren't loading.

Error: `"Cannot return null for non-nullable type: 'ID' within parent 'Notes' (/getNotes/seriesId)"`

**Comment by GeorgeBellTMH** [comment]
Let me go in and zero them all out.

**Comment by GeorgeBellTMH** [comment]
Should be fixed, they are all now seriesId=000

**Comment by JonEsparaz** [comment]
Thanks. I'll give them actual values when I finish up with #451

**Pull request merged**
