### PR TITLE
UI update for live events dropdown

### PR DESCRIPTION
**Pull request by JonEsparaz**
Per extended discussion in #722.

### CODE REVIEW

**Comment by JonEsparaz** [comment]
## Desktop screenshots (data from Good Friday)

### Initial state
desktop

### Hover 
desktop hover

### Scrolled to bottom of dropdown
desktop scroll

**Comment by JonEsparaz** [comment]
## iPad


## iPhone XR

**Comment by JonEsparaz** [comment]
One more screenshot. Here's what it would look like with less events (in the evening on Good Friday):

lessevents

**Comment by GeorgeBellTMH** [comment]
Very nice!!! @lucastbelem @deeinstereo please change your clocks and test!

**Pull request merged**
