### PR TITLE
Use relative URL to navigate to notes

### PR DESCRIPTION
**Pull request by JonEsparaz**
Fixes (maybe) #322.

The only difference I can see between notes and blogs (which are essentially the same thing) is the use of relative URLs for navigation - hopefully this resolves the issue.

### CODE REVIEW

**Comment by nikklassen** [comment]
This appears to be fixed with my refactoring of the code to support /notes in #326

**Comment by JonEsparaz** [comment]
> This appears to be fixed with my refactoring of the code to support /notes in #326

@GeorgeBellTMH let's merge this one first then.

**Comment by GeorgeBellTMH** [comment]
Assuming we will not be using this now.

**Comment by JonEsparaz** [comment]
Yup. Closing...

**Pull request closed without merging**
