### PR TITLE
Fix redirects to external pages

### LINKED ISSUE #418: Redirects to pdfs not working
When you go to themeetinghouse.com/plantoprotect, the browser displays the redirect location, but returns "page not found". That seems to be happening for all redirects that are supposed to take you to a pdf.

### PR DESCRIPTION
**Pull request by nikklassen**
Fixes #418

### CODE REVIEW

**Comment by deeinstereo** [comment]
@GeorgeBellTMH @JonEsparaz can you look at this and merge if it's good to go? All the mailto redirects are also not working atm and I need those to be running.

**Comment by JonEsparaz** [comment]
@deeinstereo the mailto issue was fixed in #420, but George needs to publish the changes.

**Comment by deeinstereo** [comment]
Gotcha! Thanks for clarifying! @JonEsparaz

**Comment by georgevicbell** [comment]
Will publish as soon as I get power back - we’ve been in a power outage since 3 last night. Toronto hydro says it should be back at 5...

Sent from my iPhone

On Aug 27, 2020, at 4:15 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

@deeinstereo<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdeeinstereo&data=02%7C01%7C%7Cb46cc2a5e8074dadb6f808d84ac5e9b2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637341561167197818&sdata=aoD7IllZ3IBE3nkCrARnTNVBW3XceAixZjc0ffHIhrI%3D&reserved=0> the mailto issue was fixed in #420<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthemeetinghouse%2Fweb%2Fpull%2F420&data=02%7C01%7C%7Cb46cc2a5e8074dadb6f808d84ac5e9b2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637341561167207801&sdata=0gtaDWkzi1v%2BlPFzI7yvP2hiJVE8Wfc6gCT15owELp8%3D&reserved=0>, but George needs to publish the changes.

**Comment by deeinstereo** [comment]
Yikes! God speed @GeorgeBellTMH !

**Comment by GeorgeBellTMH** [comment]
Good to go!

**Pull request merged**
