### PR TITLE
Connect form & other fixes

### LINKED ISSUE #162: Connect form glitch
There is an issue with where the form is being populated over the graphics.
Screen Shot 2020-04-28 at 9 04 40 AM

### PR DESCRIPTION
**Pull request by JonEsparaz**
Resolves #162.

Additional fixes for similar and/or related issues found on other popup-style pages including: go-pledge, volunteer, peacemakers-give, weather, give, go-give, kidmaxchallenge and covid19.

### CODE REVIEW

**Comment by GeorgeBellTMH** [comment]
In Safari - under give/online banking - on desktop - scroll isn't working...menu is lost below bottom of screen.

In Safari - under connect - on mobile - some screen sizes - button is chopped off/can't submit

**Comment by JonEsparaz** [comment]
> In Safari - under give/online banking - on desktop - scroll isn't working...menu is lost below bottom of screen.
> 
> In Safari - under connect - on mobile - some screen sizes - button is chopped off/can't submit

I can't recreate the second bug. Smaller screen sizes for mobile? Landscape or portrait?

**Comment by GeorgeBellTMH** [comment]
500x900 does it for me (I just resize safari on desktop)

**Comment by JonEsparaz** [comment]
Second issue resolve. Should be good to go.

**Pull request closed without merging**
