### PR TITLE
Convert a tags to React Router Links

### LINKED ISSUE #359: Links cause full page reloads
It looks like we are using the NavLink component from react bootstrap, instead of the NavLink component from React Router. They serve different purposes, boostrap NavLink handles only handles styling, so we aren't benefiting from the optimizations of React Router only replacing the current components, saving us from reloading/repainting the entire page.

### PR DESCRIPTION
**Pull request by nikklassen**
Using a tags/modifying location.href causes the whole page to reload for every navigation. React Router's Link uses the history API to avoid this and only rerenders components affected by routing.

Fixes #359.

There may be some styling issues now that component styles are not reloaded one every page. I've fixed all the ones I've found (mainly blogs), but if you see other ones it will just involve making sure those styles are scoped to the component they are supposed to target.

### CODE REVIEW

**Comment by JonEsparaz** [comment]
Some style issues with the <LinkButton> component:

iPad portrait mode, teaching page:
localhost_3006_(iPad)

Desktop, teaching page (on hover):
image

**Comment by nikklassen** [comment]
Thanks @JonEsparaz, fixed

**Comment by GeorgeBellTMH** [comment]
Reverted due to style issues with underlines in footer...probably need to go through and ensure they all maintain style.

**Comment by JonEsparaz** [comment]
Another style bug I just saw while checking out the footer:

image

ContentItem links have a double underline (I think a text decoration is being displayed).

**Pull request merged**
