### PR TITLE
Search icon changes

### LINKED ISSUE #409: Search icon change
This should be locked to the top of every page so always accessible. (except for dialog boxes, overlays, forms, video player)

Can this go back in a white box. Just concerned that if a photo has a dark area at the top corner, we'll lose the icon. Also, make the icon 40% smaller than current size and make sure it's not sitting edge to edge in a white box. It should have some room around it.

### PR DESCRIPTION
**Pull request by itbel**
search icon changes: 
- white background added for visibility
- added padding and resized 
- is now fixed when scrolling the page
resolves #409

### CODE REVIEW

**Comment by JonEsparaz** [comment]
@itbel some quick feedback.

Unfortunately, our website has some vertical scroll, so `right: 0` causes this on iPad (the icon is partially cut off):


Also, on desktop, the icon is super tiny:
Screenshot from 2020-09-25 00-25-14

Or if I'm in split-screen, I can't see the icon at all:

**Comment by itbel** [comment]
Thank you for the feedback. I'll revisit this tomorrow.

**Comment by itbel** [comment]
@JonEsparaz Did you mean horizontal scrolling? 
If so, is this intended behavior? If it is not, then changing this could allow right:0 to work.
overflowing_vp

**Comment by JonEsparaz** [comment]
This vertical scroll is not intentional. Feel free to get rid of it if needed.

**Comment by itbel** [comment]
I've made adjustments to the icon size so it is more visible in smaller screens. As for the icon getting cut off, this could have something to do with issue #486. I did, however, test these changes on lambdatest on a few different iPads and the icon is fixed in the appropriate position. It seems like what you saw could be a dev tools specific issue (if that's what you were using) because it is not showing on the simulator. I also tried this on my tab S2 and it's working fine. More testing could be required.
NewSearchIcon

**Comment by itbel** [comment]
I wasn't sure exactly if I should be using pixels or viewport units. I set the minimum size of the icon to the specified size on Figma.

**Pull request merged**
